set paths_array(margin_msg,1) {}
set paths_array(e_line,1) {0}
set paths_array(req_time,1) {8.999}
set paths_array(slack,1) {-1.588}
set paths_array(TS,1) {}
set paths_array(start_point,1) {bg_grayscale/blue[0]}
set paths_array(end_clk_dly,1) {0.000}
set paths_array(start_clock,1) {motion_detect_top|clk:rising}
set paths_array(skew,1) {0.0}
set paths_array(sig) {/home/icl5712/GitHub/CE387/Lab3/proj_1.prj|rev_3 {} /home/icl5712/GitHub/CE387/Lab3/rev_3/sdc_verif_slack.itd correlate 1 slack 1 {} {} {} {} {} {} 0 1 0 1 1}
set paths_array(margin,1) {0}
set paths_array(pro_slack,1) {0}
set paths_array(start_type,1) {reg}
set paths_array(start_clk_dly,1) {0.000}
set paths_array(index,1) {1}
set paths_array(passed,1) {0}
set paths_array(end_point,1) {bg_grayscale/grayscale[0]}
set paths_array(end_type,1) {reg}
set paths_array(data_delay,1) {0}
set paths_array(status_msg,1) {}
set paths_array(s_line,1) {0}
set paths_array(end_clock,1) {motion_detect_top|clk:rising}
set synth_array(start_clk_dly,1) {}
set synth_array(start_type,1) {}
set synth_array(start_point,1) {}
set synth_array(end_clk_dly,1) {}
set synth_array(end_type,1) {}
set synth_array(end_point,1) {}
set synth_array(start_clock,1) {}
set synth_array(skew,1) {}
set synth_array(slack,1) {}
set synth_array(req_time,1) {}
set synth_array(end_clock,1) {}
set sort_list {1 NA}
set clock_list {}
set foo {ctd_ta_point,bg_grayscale/grayscale[0]}
set ta_array($foo) {bg_grayscale.grayscale[0]}
set foo {ctd_ta_point,bg_grayscale/blue[0]}
set ta_array($foo) {bg_grayscale.blue[0]}
puts ""
